#!/bin/sh /etc/rc.common
#
# Copyright (C) 2015 OpenWrt-dist
# Copyright (C) 2016 fw867 <ffkykzs@gmail.com>
# Copyright (C) 2024 iv7777 <hongba@rocketmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99
CONFIG="timewol"
CRONTAB_FILE="/etc/crontabs/root"
ETHERWAKE_CMD="/usr/bin/etherwake"

# 从 UCI 配置中获取值，支持默认值
uci_get_by_type() {
	local type=$1 option=$2 default=$3 index=${4:-0}
	uci get "$CONFIG.@$type[$index].$option" 2>/dev/null || echo "$default"
}

# 判断布尔值是否为真
is_true() {
	case "$1" in
		1|on|true|yes|enabled) return 0 ;;
		*) return 1 ;;
	esac
}

# 加载配置，判断是否启用
load_config() {
	is_true "$(uci_get_by_type basic enable "0")"
}

# 清理 crontab 中的 etherwake 规则
clear_crontab() {
	sed -i '/etherwake/d' "$CRONTAB_FILE"
}

# 添加 WoL 规则到 crontab
add_rule() {
	clear_crontab
	for i in $(seq 0 100); do
		local macaddr maceth minute hour day month weeks

		macaddr=$(uci_get_by_type macclient macaddr "" "$i")
		maceth=$(uci_get_by_type macclient maceth "" "$i")

		# 必填字段检查
		[ -z "$macaddr" ] && break
		[ -z "$maceth" ] && break

		# 获取时间参数，设置默认值
		minute=$(uci_get_by_type macclient minute "0" "$i")
		hour=$(uci_get_by_type macclient hour "*" "$i")
		day=$(uci_get_by_type macclient day "*" "$i")
		month=$(uci_get_by_type macclient month "*" "$i")
		weeks=$(uci_get_by_type macclient weeks "*" "$i")

		# 添加规则
		echo "$minute $hour $day $month $weeks $ETHERWAKE_CMD -b -D -i $maceth $macaddr" >> "$CRONTAB_FILE"
	done
}

# 启动服务
start() {
	load_config && add_rule
}

# 停止服务
stop() {
	clear_crontab
}